# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: tbar 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "tbar".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Hinegardner".freeze]
  s.date = "2018-05-19"
  s.description = "A personal / small business accounting thing".freeze
  s.email = "jeremy@copiousfreetime.org".freeze
  s.extra_rdoc_files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "Manifest.txt".freeze, "README.md".freeze]
  s.files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "LICENSE".freeze, "Manifest.txt".freeze, "README.md".freeze, "Rakefile".freeze, "lib/tbar.rb".freeze, "spec/spec_helper.rb".freeze, "spec/version_spec.rb".freeze, "tasks/default.rake".freeze, "tasks/extension.rake".freeze, "tasks/this.rb".freeze]
  s.homepage = "http://github.com/copiousfreetime/tbar".freeze
  s.licenses = ["ISC".freeze]
  s.rdoc_options = ["--main".freeze, "README.md".freeze, "--markup".freeze, "tomdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new("= 2.4.0".freeze)
  s.rubygems_version = "2.7.6".freeze
  s.summary = "A personal / small business accounting thing".freeze
  s.test_files = ["spec/spec_helper.rb".freeze, "spec/version_spec.rb".freeze]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<highline>.freeze, ["~> 1.7"])
      s.add_runtime_dependency(%q<money>.freeze, ["~> 6.11"])
      s.add_runtime_dependency(%q<monetize>.freeze, ["~> 1.0"])
      s.add_runtime_dependency(%q<sequel>.freeze, ["~> 5.8"])
      s.add_runtime_dependency(%q<pg>.freeze, ["~> 1.0"])
      s.add_runtime_dependency(%q<trollop>.freeze, ["~> 2.1"])
      s.add_development_dependency(%q<rake>.freeze, ["~> 12.1"])
      s.add_development_dependency(%q<minitest>.freeze, ["~> 5.11"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 6.0"])
      s.add_development_dependency(%q<simplecov>.freeze, ["~> 0.16"])
    else
      s.add_dependency(%q<highline>.freeze, ["~> 1.7"])
      s.add_dependency(%q<money>.freeze, ["~> 6.11"])
      s.add_dependency(%q<monetize>.freeze, ["~> 1.0"])
      s.add_dependency(%q<sequel>.freeze, ["~> 5.8"])
      s.add_dependency(%q<pg>.freeze, ["~> 1.0"])
      s.add_dependency(%q<trollop>.freeze, ["~> 2.1"])
      s.add_dependency(%q<rake>.freeze, ["~> 12.1"])
      s.add_dependency(%q<minitest>.freeze, ["~> 5.11"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 6.0"])
      s.add_dependency(%q<simplecov>.freeze, ["~> 0.16"])
    end
  else
    s.add_dependency(%q<highline>.freeze, ["~> 1.7"])
    s.add_dependency(%q<money>.freeze, ["~> 6.11"])
    s.add_dependency(%q<monetize>.freeze, ["~> 1.0"])
    s.add_dependency(%q<sequel>.freeze, ["~> 5.8"])
    s.add_dependency(%q<pg>.freeze, ["~> 1.0"])
    s.add_dependency(%q<trollop>.freeze, ["~> 2.1"])
    s.add_dependency(%q<rake>.freeze, ["~> 12.1"])
    s.add_dependency(%q<minitest>.freeze, ["~> 5.11"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 6.0"])
    s.add_dependency(%q<simplecov>.freeze, ["~> 0.16"])
  end
end
